### 회원가입
POST http://34.64.48.240:8080/auth/sign-up
Content-Type: application/json

{
  "email": "abcde@gmail.com",
  "password": "12345678"
}

### 로그인
POST http://34.64.48.240:8080/auth/sign-in
Content-Type: application/json

{
  "email": "abcde@gmail.com",
  "password": "12345678"
}

### 토큰 재발급
POST http://34.64.48.240:8080/auth/reissue
Content-Type: application/json

{
  "refreshToken":"eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2OTEyMjAxNTMsImV4cCI6MTY5MjQyOTc1M30.cci-1lhCHBZQe6st7J-PgZ0rKHhlx_DJEZjtx2WL3so"
}

### 게시글 생성
POST http://34.64.48.240:8080/posts
Content-Type: application/json
Authorization: Bearer {accessToken}

{
    "title":"출시 100일' 나이트크로우 매출 상위권...위메이드 장기 흥행 노린다",
    "content":"지난 4월 국내 출시된 나이트 크로우는 4일 서비스 100일을 넘긴 최근까지 구글 플레이, 애플 앱스토어 매출 최상위권을 유지하고 있다. 이 게임은 중세 유럽 기반의 신규 지식재산(IP)으로, 제4차 십자군 전쟁이 끝난 직후 혼돈스러운 유럽을 바탕으로 하는 세계관과 국"
}

### 게시글 수정
PUT http://34.64.48.240:8080/posts/2
Content-Type: application/json
Authorization: Bearer {accessToken}

{
  "title":"제목 수정입니다",
  "content":"콘텐츠도 수정입니다"
}

### 게시글 삭제
DELETE http://34.64.48.240:8080/posts/2
Content-Type: application/json
Authorization: Bearer {accessToken}

### 게시글 상세 조회
GET http://34.64.48.240:8080/posts/1
Content-Type: application/json
Authorization: Bearer {accessToken}

### 게시글 목록 조회
GET http://34.64.48.240:8080/posts?page=0
Content-Type: application/json
Authorization: Bearer {accessToken}

